project:
  type: website
  resources:
    - "css/"
    - "js/"
    - "*.html"

website:
  title: "Chulalongkorn University’s Metabolomics for Life Sciences Research Unit"
  site-url: "https://cumetabolomics.github.io"
  repo-url: "https://github.com/cumetabolomics"
  favicon: file/path/to/image.png
  # google-analytics: "UA-177339812-1"
  twitter-card: true
  #back-to-top-navigation: true
  page-navigation: false
  search: true
  
  navbar:
    search: true
    title: false
    logo-alt: "CU-Metabolomics"
    # background: "#F6F5F3"
    logo: assets/img/logo.png
    right: 
      - icon: github
        href: https://github.com/cumetabolomics
      - icon: twitter
        href: https://twitter.com/
      
    left:
      - href: index.qmd
        text: Home
      - text: "Research"
        href: research/research.qmd
      - text: "Publication"
        href: publication/index.qmd
      - text: Members
        href: member/index.qmd
      - about.qmd
  page-footer: 
    background: "#F6F5F3"
    center: Copyright © 2024, Natapol Pornputtapong Made with 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
    

format:
  html:
    theme: minty.scss
    toc: true



